CC=gcc
CFLAGS=-c -Wall -std=c11 -pedantic -ansi
LDFLAGS=
SOURCES=puzzle.c
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=puzzle

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.c.o:
	$(CC) $(CFLAGS) $< -o $@

clean: 
	rm *.exe *.o
	echo Clean done